import { type Habit } from './types';
import { format, subDays } from 'date-fns';

export const initialHabits: Habit[] = [
  {
    id: '1',
    name: 'Read for 20 minutes',
    priority: 'Medium',
    frequency: 'Daily',
    trackingType: 'Quantitative',
    goalValue: 20,
    goalUnit: 'minutes',
    completed: {
      [format(subDays(new Date(), 1), 'yyyy-MM-dd')]: 25,
      [format(subDays(new Date(), 2), 'yyyy-MM-dd')]: 20,
      [format(subDays(new Date(), 4), 'yyyy-MM-dd')]: 15,
    },
    category: 'Personal Growth',
  },
  {
    id: '2',
    name: 'Morning workout',
    priority: 'High',
    frequency: 'Custom',
    days: ['Mon', 'Wed', 'Fri'],
    trackingType: 'Checkbox',
    completed: {
      [format(subDays(new Date(), 1), 'yyyy-MM-dd')]: 1,
      [format(subDays(new Date(), 3), 'yyyy-MM-dd')]: 0,
      [format(subDays(new Date(), 4), 'yyyy-MM-dd')]: 1,
    },
    category: 'Health',
  },
  {
    id: '3',
    name: 'Drink 8 glasses of water',
    priority: 'Medium',
    frequency: 'Daily',
    trackingType: 'Quantitative',
    goalValue: 8,
    goalUnit: 'glasses',
    completed: {
      [format(subDays(new Date(), 1), 'yyyy-MM-dd')]: 8,
      [format(subDays(new Date(), 2), 'yyyy-MM-dd')]: 6,
    },
    category: 'Health',
  },
  {
    id: '4',
    name: 'Plan tomorrow\'s tasks',
    priority: 'Low',
    frequency: 'Daily',
    trackingType: 'Checkbox',
    completed: {
      [format(new Date(), 'yyyy-MM-dd')]: 0,
    },
    category: 'Productivity',
  },
   {
    id: '5',
    name: 'Weekly review',
    priority: 'High',
    frequency: 'Weekly',
    trackingType: 'Checkbox',
    completed: {},
    category: 'Productivity',
  },
  {
    id: '6',
    name: 'Meditate for 10 minutes',
    priority: 'Medium',
    frequency: 'Daily',
    trackingType: 'Quantitative',
    goalValue: 10,
    goalUnit: 'minutes',
    completed: {},
    category: 'Mindfulness',
  },
  {
    id: '7',
    name: 'Journal for 5 minutes',
    priority: 'Low',
    frequency: 'Daily',
    trackingType: 'Checkbox',
    completed: {},
    category: 'Mindfulness',
  },
  {
    id: '8',
    name: 'Walk 10,000 steps',
    priority: 'Medium',
    frequency: 'Daily',
    trackingType: 'Quantitative',
    goalValue: 10000,
    goalUnit: 'steps',
    completed: {},
    category: 'Health',
  },
];
