import { type Habit } from './types';
import { format, subDays } from 'date-fns';

export const initialHabits: Habit[] = [
  {
    id: '1',
    name: 'Wakeup before Fajr',
    priority: 'High',
    frequency: 'Daily',
    trackingType: 'Checkbox',
    completed: {},
    category: 'Spiritual',
  },
  {
    id: '2',
    name: '5 Times Prayer',
    priority: 'High',
    frequency: 'Daily',
    trackingType: 'Quantitative',
    goalValue: 5,
    goalUnit: 'times',
    completed: {},
    category: 'Spiritual',
  },
  {
    id: '3',
    name: 'Quran Read',
    priority: 'Medium',
    frequency: 'Daily',
    trackingType: 'Checkbox',
    completed: {},
    category: 'Spiritual',
  },
  {
    id: '4',
    name: 'Book Read',
    priority: 'Medium',
    frequency: 'Daily',
    trackingType: 'Checkbox',
    completed: {},
    category: 'Personal Growth',
  },
   {
    id: '5',
    name: 'Sleep Before 10.30',
    priority: 'Medium',
    frequency: 'Daily',
    trackingType: 'Checkbox',
    completed: {},
    category: 'Health',
  },
  {
    id: '6',
    name: 'Skin Care',
    priority: 'Low',
    frequency: 'Daily',
    trackingType: 'Checkbox',
    completed: {},
    category: 'Health',
  },
  {
    id: '7',
    name: '4 L Water',
    priority: 'Medium',
    frequency: 'Daily',
    trackingType: 'Quantitative',
    goalValue: 4,
    goalUnit: 'L',
    completed: {},
    category: 'Health',
  },
  {
    id: '8',
    name: 'Journaling',
    priority: 'Low',
    frequency: 'Daily',
    trackingType: 'Checkbox',
    completed: {},
    category: 'Personal Growth',
  },
    {
    id: '9',
    name: 'Track Finances',
    priority: 'Medium',
    frequency: 'Daily',
    trackingType: 'Checkbox',
    completed: {},
    category: 'Finance',
  },
  {
    id: '10',
    name: '7000 steps',
    priority: 'Medium',
    frequency: 'Daily',
    trackingType: 'Quantitative',
    goalValue: 7000,
    goalUnit: 'steps',
    completed: {},
    category: 'Health',
  },
];
